#!/usr/bin/env node
// gen-codemap.mjs — scan js/*.js for top-level exported symbols and write
// CODEMAP.md, grouped by file, each symbol with the file + a one-line purpose
// inferred from a leading `//` comment when present. Deterministic (sorted),
// LF line endings, no dependencies. Run from the project root:
//   node scripts/gen-codemap.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const JS_DIR = join(ROOT, "js");

// match a top-level export of a function / const / class, capturing the name.
// (^\s* keeps it to declarations; we additionally skip indented ones below.)
const EXPORT_RE = /^export\s+(?:async\s+)?(function|const|let|class)\s+([A-Za-z_$][\w$]*)/;

// derive a one-line purpose: the nearest preceding run of // comment lines.
function purposeFor(lines, idx){
  const out = [];
  for(let i = idx - 1; i >= 0; i--){
    const t = lines[i].trim();
    if(t.startsWith("//")){ out.unshift(t.replace(/^\/\/+\s?/, "").trim()); }
    else if(t === ""){ if(out.length) break; }   // blank after a comment block ends it
    else break;                                    // hit code -> stop
  }
  if(!out.length) return "";
  // collapse the comment block into one line, trim trailing punctuation noise.
  return out.join(" ").replace(/\s+/g, " ").trim();
}

function scanFile(path){
  const src = readFileSync(path, "utf8");
  const lines = src.split(/\r?\n/);
  const syms = [];
  lines.forEach((line, i) => {
    const m = EXPORT_RE.exec(line);
    if(m){ syms.push({ kind: m[1], name: m[2], line: i + 1, purpose: purposeFor(lines, i) }); }
  });
  syms.sort((a, b) => a.name.localeCompare(b.name));
  return syms;
}

const files = readdirSync(JS_DIR).filter(f => f.endsWith(".js")).sort((a, b) => a.localeCompare(b));

let out = "";
out += "# CODEMAP — LootNShoot\n\n";
out += "Auto-generated by `scripts/gen-codemap.mjs` — do not edit by hand. Re-run\n";
out += "`node scripts/gen-codemap.mjs` after moving or renaming any exported symbol.\n\n";
out += "Index of every top-level exported symbol in `js/*.js`, grouped by file.\n\n";

for(const f of files){
  const syms = scanFile(join(JS_DIR, f));
  out += `## js/${f}\n\n`;
  if(!syms.length){ out += "_no top-level exports_\n\n"; continue; }
  for(const s of syms){
    const where = `js/${f}:${s.line}`;
    out += `- \`${s.name}\` (${s.kind}) — ${where}`;
    out += s.purpose ? ` — ${s.purpose}\n` : "\n";
  }
  out += "\n";
}

writeFileSync(join(ROOT, "CODEMAP.md"), out.replace(/\r\n/g, "\n"), "utf8");
console.log(`CODEMAP.md written: ${files.length} files scanned.`);
